name: V20
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.18
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blosc=1.21.5
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fiona=1.9.6
  - fmt=10.2.1
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.8.5
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geos=3.12.1
  - geotiff=1.7.1
  - giflib=5.2.2
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - json-c=0.17
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.8.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.5
  - munkres=1.1.4
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nspr=4.35
  - nss=3.98
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.1
  - plotly=5.22.0
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - proj=9.4.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-fastjsonschema=2.19.1
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyzmq=26.0.2
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.31.0
  - rpds-py=0.18.1
  - rtree=1.2.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=69.5.1
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.2.0
  - spdlog=1.13.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tenacity=8.2.3
  - threadpoolctl=3.5.0
  - tiledb=2.22.0
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzcode=2024a
  - tzdata=2024a
  - uriparser=0.9.7
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.4.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - bottleneck==1.3.8
      - cloudpickle==3.0.0
      - dask==2024.4.2
      - deprecation==2.1.0
      - fsspec==2024.3.1
      - highspy==1.5.3
      - linopy==0.3.8
      - locket==1.0.0
      - numexpr==2.10.0
      - orjson==3.10.1
      - partd==1.4.1
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydantic-settings==2.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pyyaml==6.0.1
      - toolz==0.12.1
      - tqdm==4.66.2
      - tz-osemosys==0.0.1
      - xarray==2024.3.0
      - zipp==3.18.1
